### ISSUE TITLE
US10, US25, US52... - Display translation request

### ISSUE THREAD

**Issue by gabibguedes** [translate-me/translate-me#54]
Make an endpoint for viewing translation requests, it should work with filters for searching one or many translation requests.

**Tasks:**
- [x] View a translation request by ID
- [x] View for a search of translation requests (by name, category, author...)
- [x] View all translation requests
- [x] Use swagger to document the endpoint 

**Acceptance Criteria:**
- [x] The translation can be viewed
- [x] The author can see his translations
- [x] The translator can search for new texts
- [x] All translations can be seen
- [x] The code is passing on code climate
- [x] The endpoint is documented

*OBS.:* Search Rest Filter
