### ISSUE TITLE
US59, US60 - Count number of words

### ISSUE THREAD

**Issue by gabibguedes** [translate-me/translate-me#55]
Make an endpoint to count the number of words and generate information about the value of the text, and how much should be payed for every translator and revisor.

**Tasks:**
- [x] Count words on fragments of the text
- [x] Count words on text
- [ ] Calculate the security of the text
- [x] Generate a value each translator should receive
- [ ] Generate a value each revisor should receive
- [x] Calculate how much the client must pay
- [ ] Use swagger to document the endpoint

**Acceptance Criteria:**
 - [x] The text and it's fragments has a value
 - [ ] The text has a security percentage
 - [ ] The code is passing on code climate
 - [ ] The endpoint is documented

**Comment by mbslet** [comment]
As you go through the whole file, you can use the split () method to capture each word of the text, and then using the len method, you get the number of words.
Maybe help, i think :D

**Comment by aleronupe** [comment]
The value defined to each revisor to receive doesn't seem to be useful being done at this issue. This value will be calculated at the function that sends a fragment to revision, according to what was defined at the database documentation. Should the calculations be done anyway, once they would not be saved at the database structure?
